### ISSUE TITLE
Fix: Not Syncing Item From ERPNext 

### ISSUE THREAD

**Issue by sammish** [bailabs/tailpos#29]
Not Syncing Item From ERPNext and getting this error 
![image](https://user-images.githubusercontent.com/12432802/57454211-f727e000-7270-11e9-8021-9ddc4e2bc351.png)

**Comment by sammish** [comment]
If I Set POS profile here it will be sync 

![image](https://user-images.githubusercontent.com/12432802/57454635-f93e6e80-7271-11e9-8b04-b1c1983fe82c.png)

**Comment by sammish** [comment]
Device POS Profile Not working 

![image](https://user-images.githubusercontent.com/12432802/57454670-1115f280-7272-11e9-9b4f-93b6a337dc2a.png)

**Comment by iRaySpace** [comment]
Hello @sammish 
This issue is resolved. The update will be ready few moments from now. Please update both your ERPNext and TailPOS. Just refer below, thanks!
![image](https://user-images.githubusercontent.com/5818544/57508154-54846580-7333-11e9-9c85-2c86456f3434.png)
![image](https://user-images.githubusercontent.com/5818544/57508290-b80e9300-7333-11e9-8da2-0032bc73a7f0.png)
